// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoreKFragRequest {
    #[prost(string, tag = "1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub member_pk: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub kfrag: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoreKFragResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReEncryptRequest {
    /// Identifies which stored kfrag to use.
    #[prost(string, tag = "1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub member_pk: ::prost::alloc::vec::Vec<u8>,
    /// Serialized Umbral Capsule from the encrypted content.
    #[prost(bytes = "vec", tag = "4")]
    pub capsule: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReEncryptResponse {
    /// Serialized VerifiedCapsuleFrag — the re-encrypted capsule fragment.
    #[prost(bytes = "vec", tag = "1")]
    pub cfrag: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteKFragsRequest {
    #[prost(string, tag = "1")]
    pub org_id: ::prost::alloc::string::String,
    /// Member's PRE public key (serialized Umbral PublicKey).
    #[prost(bytes = "vec", tag = "2")]
    pub member_pk: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteKFragsResponse {
    /// Number of kfrags deleted.
    #[prost(uint32, tag = "1")]
    pub deleted_count: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrgKFragsRequest {
    #[prost(string, tag = "1")]
    pub org_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrgKFragsResponse {
    #[prost(uint32, tag = "1")]
    pub deleted_count: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// Number of kfrags currently stored.
    #[prost(uint64, tag = "2")]
    pub kfrag_count: u64,
    /// Umbral library version.
    #[prost(string, tag = "3")]
    pub umbral_version: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod umbral_sidecar_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// UmbralSidecar provides Proxy Re-Encryption operations via the umbral-pre crate.
    /// This service runs as a separate process to maintain GPL-3.0 / Apache-2.0 license boundary.
    /// All byte fields are serialized Umbral types using MessagePack (DefaultSerialize/DefaultDeserialize).
    #[derive(Debug, Clone)]
    pub struct UmbralSidecarClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UmbralSidecarClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UmbralSidecarClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UmbralSidecarClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UmbralSidecarClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// StoreKFrag stores a pre-generated kfrag for (org_id, member_pubkey).
        /// Used when kfrags are generated on the leader machine.
        pub async fn store_k_frag(
            &mut self,
            request: impl tonic::IntoRequest<super::StoreKFragRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StoreKFragResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/umbral.v1.UmbralSidecar/StoreKFrag",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("umbral.v1.UmbralSidecar", "StoreKFrag"));
            self.inner.unary(req, path, codec).await
        }
        /// ReEncrypt applies a stored kfrag to a capsule, producing a cfrag.
        /// Called by the hub during memory retrieval.
        /// Returns an error if no kfrag exists for the specified (org_id, member_pubkey).
        pub async fn re_encrypt(
            &mut self,
            request: impl tonic::IntoRequest<super::ReEncryptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReEncryptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/umbral.v1.UmbralSidecar/ReEncrypt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("umbral.v1.UmbralSidecar", "ReEncrypt"));
            self.inner.unary(req, path, codec).await
        }
        /// DeleteKFrags deletes all stored kfrags for a member in an org.
        /// Called by the hub when a member is removed (triggered by MemberRemoved chain event).
        /// Idempotent — returns success even if no kfrags exist.
        pub async fn delete_k_frags(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteKFragsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteKFragsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/umbral.v1.UmbralSidecar/DeleteKFrags",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("umbral.v1.UmbralSidecar", "DeleteKFrags"));
            self.inner.unary(req, path, codec).await
        }
        /// DeleteOrgKFrags deletes ALL stored kfrags for an entire org.
        /// Called during org dissolution.
        pub async fn delete_org_k_frags(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteOrgKFragsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteOrgKFragsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/umbral.v1.UmbralSidecar/DeleteOrgKFrags",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("umbral.v1.UmbralSidecar", "DeleteOrgKFrags"));
            self.inner.unary(req, path, codec).await
        }
        /// Health returns the sidecar's status.
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/umbral.v1.UmbralSidecar/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("umbral.v1.UmbralSidecar", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod umbral_sidecar_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with UmbralSidecarServer.
    #[async_trait]
    pub trait UmbralSidecar: std::marker::Send + std::marker::Sync + 'static {
        /// StoreKFrag stores a pre-generated kfrag for (org_id, member_pubkey).
        /// Used when kfrags are generated on the leader machine.
        async fn store_k_frag(
            &self,
            request: tonic::Request<super::StoreKFragRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StoreKFragResponse>,
            tonic::Status,
        >;
        /// ReEncrypt applies a stored kfrag to a capsule, producing a cfrag.
        /// Called by the hub during memory retrieval.
        /// Returns an error if no kfrag exists for the specified (org_id, member_pubkey).
        async fn re_encrypt(
            &self,
            request: tonic::Request<super::ReEncryptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReEncryptResponse>,
            tonic::Status,
        >;
        /// DeleteKFrags deletes all stored kfrags for a member in an org.
        /// Called by the hub when a member is removed (triggered by MemberRemoved chain event).
        /// Idempotent — returns success even if no kfrags exist.
        async fn delete_k_frags(
            &self,
            request: tonic::Request<super::DeleteKFragsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteKFragsResponse>,
            tonic::Status,
        >;
        /// DeleteOrgKFrags deletes ALL stored kfrags for an entire org.
        /// Called during org dissolution.
        async fn delete_org_k_frags(
            &self,
            request: tonic::Request<super::DeleteOrgKFragsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteOrgKFragsResponse>,
            tonic::Status,
        >;
        /// Health returns the sidecar's status.
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
    }
    /// UmbralSidecar provides Proxy Re-Encryption operations via the umbral-pre crate.
    /// This service runs as a separate process to maintain GPL-3.0 / Apache-2.0 license boundary.
    /// All byte fields are serialized Umbral types using MessagePack (DefaultSerialize/DefaultDeserialize).
    #[derive(Debug)]
    pub struct UmbralSidecarServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> UmbralSidecarServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for UmbralSidecarServer<T>
    where
        T: UmbralSidecar,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/umbral.v1.UmbralSidecar/StoreKFrag" => {
                    #[allow(non_camel_case_types)]
                    struct StoreKFragSvc<T: UmbralSidecar>(pub Arc<T>);
                    impl<
                        T: UmbralSidecar,
                    > tonic::server::UnaryService<super::StoreKFragRequest>
                    for StoreKFragSvc<T> {
                        type Response = super::StoreKFragResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StoreKFragRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UmbralSidecar>::store_k_frag(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StoreKFragSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/umbral.v1.UmbralSidecar/ReEncrypt" => {
                    #[allow(non_camel_case_types)]
                    struct ReEncryptSvc<T: UmbralSidecar>(pub Arc<T>);
                    impl<
                        T: UmbralSidecar,
                    > tonic::server::UnaryService<super::ReEncryptRequest>
                    for ReEncryptSvc<T> {
                        type Response = super::ReEncryptResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReEncryptRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UmbralSidecar>::re_encrypt(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReEncryptSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/umbral.v1.UmbralSidecar/DeleteKFrags" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteKFragsSvc<T: UmbralSidecar>(pub Arc<T>);
                    impl<
                        T: UmbralSidecar,
                    > tonic::server::UnaryService<super::DeleteKFragsRequest>
                    for DeleteKFragsSvc<T> {
                        type Response = super::DeleteKFragsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteKFragsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UmbralSidecar>::delete_k_frags(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteKFragsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/umbral.v1.UmbralSidecar/DeleteOrgKFrags" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteOrgKFragsSvc<T: UmbralSidecar>(pub Arc<T>);
                    impl<
                        T: UmbralSidecar,
                    > tonic::server::UnaryService<super::DeleteOrgKFragsRequest>
                    for DeleteOrgKFragsSvc<T> {
                        type Response = super::DeleteOrgKFragsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteOrgKFragsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UmbralSidecar>::delete_org_k_frags(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteOrgKFragsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/umbral.v1.UmbralSidecar/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: UmbralSidecar>(pub Arc<T>);
                    impl<
                        T: UmbralSidecar,
                    > tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UmbralSidecar>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for UmbralSidecarServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "umbral.v1.UmbralSidecar";
    impl<T> tonic::server::NamedService for UmbralSidecarServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
